<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\Container5g4yhtu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5g4yhtu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5g4yhtu.legacy');
=======
if (\class_exists(\ContainerXXKA8xZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXKA8xZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXKA8xZ.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\Container5g4yhtu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5g4yhtu\App_KernelDevDebugContainer([
    'container.build_hash' => '5g4yhtu',
    'container.build_id' => 'b4f8500b',
    'container.build_time' => 1648707988,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5g4yhtu');
=======
    \class_alias(\ContainerXXKA8xZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXKA8xZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXKA8xZ',
    'container.build_id' => 'd17c603b',
    'container.build_time' => 1651741721,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXKA8xZ');
>>>>>>> Stashed changes
